Update de_DE.lang
MightyPirates/OpenComputers pull request #2091
Opened 2016-10-09 10:44 UTC by Nex4rius

2016-10-10 09:35 UTC, dgelessus commented on src/main/resources/assets/opencomputers/lang/de_DE.lang
> +oc:gui.Chat.WarningPower=Es ist kein unterstützter, Strom erzeugender Mod verfügbar. Computer, Bildschirme und alle anderen Komponenten werden §lkeine§f Energie benötigen. Installiere eine der folgen
Manche Leute behaupten, dass es "die Mod" ist, weil "Modifikation" ja weiblich ist. Persönlich bin ich der Meinung, dass "der Mod" einfach besser klingt, das müsste dann aber @fnuecke entscheiden.

2016-10-10 09:35 UTC, dgelessus commented on src/main/resources/assets/opencomputers/lang/de_DE.lang
> +oc:tooltip.Analyzer=Erlaubt es, Informationen über Blöcke anzuzeigen, wie zum Beispiel ihre §fAdresse§7 und ihren §fKomponentennamen§7.[nl] Erlaubt zudem, den Fehler anzuzeigen, der zu einem Computer
Das "zum Bleistift" ist Absicht (habe ich bereits versucht zu "korrigieren" `:)`)

2016-10-10 09:35 UTC, dgelessus commented on src/main/resources/assets/opencomputers/lang/de_DE.lang
> +achievement.oc.ram.desc=Gratuliere! Du machst es richtig.
"Doin' It Right" ist soweit ich weiß eine Anspielung auf Daft Punk, daher habe ich das nicht übersetzt.

2016-10-10 14:18 UTC, Nex4rius commented on src/main/resources/assets/opencomputers/lang/de_DE.lang
> +oc:tooltip.Analyzer=Erlaubt es, Informationen über Blöcke anzuzeigen, wie zum Beispiel ihre §fAdresse§7 und ihren §fKomponentennamen§7.[nl] Erlaubt zudem, den Fehler anzuzeigen, der zu einem Computer
Muss man verstehen warum es "zum Bleistift" heißen soll?

2016-10-10 14:19 UTC, Nex4rius commented on src/main/resources/assets/opencomputers/lang/de_DE.lang
> +achievement.oc.ram.desc=Gratuliere! Du machst es richtig.
Hm Ich kannte das Lied davor gar nicht, aber trotzdem bin ich der Meinung das man es übersetzen sollte.

2016-10-10 16:31 UTC, Vexatos commented on src/main/resources/assets/opencomputers/lang/de_DE.lang
> +oc:tooltip.Analyzer=Erlaubt es, Informationen über Blöcke anzuzeigen, wie zum Beispiel ihre §fAdresse§7 und ihren §fKomponentennamen§7.[nl] Erlaubt zudem, den Fehler anzuzeigen, der zu einem Computer
Uraltes Wortspiel.

2016-10-10 16:32 UTC, Vexatos commented on src/main/resources/assets/opencomputers/lang/de_DE.lang
> +oc:gui.Chat.WarningPower=Es ist kein unterstützter, Strom erzeugender Mod verfügbar. Computer, Bildschirme und alle anderen Komponenten werden §lkeine§f Energie benötigen. Installiere eine der folgen
Allgemein wird es in Mods feminin übersetzt.

2016-10-10 20:16 UTC, dgelessus commented on src/main/resources/assets/opencomputers/lang/de_DE.lang
> +oc:gui.Chat.WarningPower=Es ist kein unterstützter, Strom erzeugender Mod verfügbar. Computer, Bildschirme und alle anderen Komponenten werden §lkeine§f Energie benötigen. Installiere eine der folgen
Den Ausweg über Plural gibt es natürlich auch noch. `:)` "Es sind keine unterstützten, Strom erzeugenden Mods verfügbar." (der Vorschlag ist nicht wirklich ernst gemeint, es klingt hier recht seltsam)

2016-10-15 16:16 UTC, fnuecke commented on src/main/resources/assets/opencomputers/lang/de_DE.lang
> +oc:gui.Chat.WarningPower=Es ist kein unterstützter, Strom erzeugender Mod verfügbar. Computer, Bildschirme und alle anderen Komponenten werden §lkeine§f Energie benötigen. Installiere eine der folgen
Ich sag auch "der Mod", aber mir isses prinzipiell egal. Meine Prognose waer, dass wenn's geaendert wird der naechste PR es vmtl. wieder umdreht :P

2016-10-15 16:16 UTC, fnuecke commented on src/main/resources/assets/opencomputers/lang/de_DE.lang
> +oc:tooltip.Printer=Erlaubt es, Blöcke aus benutzerdefinierten Formen zu drucken. Verwendet Chamälium und Tintenkartuschen. Muss über einen Computer konfiguriert werden. Von Kindern fern halten. Weil
Nein. Weil halt.

2016-10-15 16:19 UTC, fnuecke commented on src/main/resources/assets/opencomputers/lang/de_DE.lang
> +achievement.oc.ram.desc=Gratuliere! Du machst es richtig.
Was dgelessus sagt. Wenn dann ne ganze Lokalisierung, ergo ne analoge Referenz auf Deutsch. Keine langweilige Verbatimuebersetzung.

2016-10-15 16:20 UTC, fnuecke commented on src/main/resources/assets/opencomputers/lang/de_DE.lang
> +achievement.oc.drone.desc=Bleib ruhig und bombardiert es vom Orbit.
Aehnlich wie unten, verbatim uebersetzte Referenzen sind doof. Entweder ganz oder gar nicht.

2016-10-15 20:46 UTC, Nex4rius commented on src/main/resources/assets/opencomputers/lang/de_DE.lang
> +achievement.oc.drone.desc=Bleib ruhig und bombardiert es vom Orbit.
Eine direkte Übersetzung ist meiner Meinung nach besser als es auf Englisch zu lassen, denn viele Leute die die deutsche Übersetzung benutzten eben KEIN englisch verstehen.

2017-11-24 08:14 UTC, payonel commented
@Vexatos can you review the work here and merge or close? thanks

2017-11-24 12:30 UTC, Vexatos requested changes

2017-11-24 12:30 UTC, Vexatos commented on src/main/resources/assets/opencomputers/lang/de_DE.lang
> +oc:gui.Chat.WarningPower=Es ist kein unterstützter, Strom erzeugender Mod verfügbar. Computer, Bildschirme und alle anderen Komponenten werden §lkeine§f Energie benötigen. Installiere eine der folgen
I would merge this if this line here wasn't changed.

2017-11-24 12:33 UTC, merged

2017-11-24 22:40 UTC, Nex4rius commented
Oh cool that was fast thanks :)
<img width=50px height=12px src="https://imgur.com/legGW9v.png" />