Added maxPacketParts method to the Network Card
MightyPirates/OpenComputers pull request #2298
Opened 2017-03-07 15:47 UTC by BrisingrAerowing

Ref #2294

2017-03-07 20:08 UTC, fnuecke commented
I'd prefer this to go into the [device info](https://github.com/BrisingrAerowing/OpenComputers/blob/9d0b7438bcac338b799b281141e493cd177506bd/src/main/scala/li/cil/oc/server/component/NetworkCard.scala#L51) (hence the "todo remove" comment on the other, similar method). As for the attribute name, I suppose "width" could do? But feel free to use something more specific.

2017-03-12 11:03 UTC, skyem123 commented
It's worth noting that I feel like it should be on the network card component because it's like the MTU of real networks?

2017-03-12 15:41 UTC, skyem123 commented
It's worth noting that I feel like it should be on the network card component because it's like the MTU of real networks?

2017-03-13 14:24 UTC, fnuecke commented
Not sure what your point is? The device info is still part of the network card component.

2017-03-13 17:18 UTC, skyem123 commented
I'm sorry... I don't really know what you're talking about with regards to "device info", as there doesn't seem to be anything on http://ocdoc.cil.li?

2017-03-13 17:24 UTC, Vexatos commented
[This](https://github.com/BrisingrAerowing/OpenComputers/blob/9d0b7438bcac338b799b281141e493cd177506bd/src/main/scala/li/cil/oc/server/component/NetworkCard.scala#L46-L52) is the device info.

2017-03-13 18:03 UTC, BrisingrAerowing commented
So how would that work? Would I add a new device attribute and set it to the value?

2017-03-13 18:04 UTC, Vexatos commented
Yes, exactly.

2017-03-13 18:13 UTC, Vexatos requested changes

2017-03-13 18:13 UTC, Vexatos commented on src/main/scala/li/cil/oc/server/component/NetworkCard.scala
> +	DeviceAttribute.MaxParts -> Settings.get.maxNetworkPacketParts.toString
Fix the indentation here.

2017-03-13 18:13 UTC, Vexatos commented on src/main/java/li/cil/oc/api/driver/DeviceInfo.java
> +		public static final String MaxParts = "maxparts"; // Maximum number of parts for, e.g. a network packet.
Fix the indentation here. I don't like the attribute name, but I can't think of anything other than @fnuecke's "width" either.

2017-03-13 18:13 UTC, Vexatos commented on src/main/java/li/cil/oc/api/driver/DeviceInfo.java
> +
Another formatting error.

2017-03-13 18:19 UTC, BrisingrAerowing commented on src/main/java/li/cil/oc/api/driver/DeviceInfo.java
> +
Already done. Notepad++ Is rather stupid when it comes to Tabs vs Spaces.

2017-03-13 18:29 UTC, Vexatos requested changes

2017-03-13 18:29 UTC, Vexatos commented on src/main/scala/li/cil/oc/server/component/NetworkCard.scala
> +    )
Still not formatted properly.

2017-03-13 18:29 UTC, Vexatos commented on src/main/java/li/cil/oc/api/driver/DeviceInfo.java
>          private DeviceAttribute() {
And an empty line here, please.

2017-03-15 02:01 UTC, closed without merging