Add bundled cable support for ComputerCraft
MightyPirates/OpenComputers pull request #2815
Opened 2018-04-17 13:12 UTC by SquidDev

This allows CC computers to read OC's bundled redstone signals and vice versa. I'm not sure how useful this actually is, but it makes things feel a little more "complete".

2018-04-17 13:17 UTC, Vexatos commented
If only there was a new proper release of CC, so that [the wireless network support](https://github.com/Vexatos/OpenComputers/compare/59e268c849bba565eb5746257200323db7804c0b...cc-wireless) could get in...

2018-04-17 13:58 UTC, Vexatos requested changes

2018-04-17 13:58 UTC, Vexatos commented on src/main/scala/li/cil/oc/integration/computercraft/BundledRedstoneProvider.scala
> +        strengths(colour) = if ((strength & (1 << colour)) == 0) 0 else 16
Shouldn't this output 15?

2018-04-17 14:00 UTC, SquidDev commented on src/main/scala/li/cil/oc/integration/computercraft/BundledRedstoneProvider.scala
> +        strengths(colour) = if ((strength & (1 << colour)) == 0) 0 else 16
Yes. I forgot to push. Sorry.

2018-04-17 14:02 UTC, Vexatos approved these changes

2018-07-04 08:21 UTC, asiekierka commented
LGTM

2018-07-04 15:56 UTC, merged

2018-07-04 16:20 UTC, SquidDev commented
Thank you!