Revamp zh_cn manual
MightyPirates/OpenComputers pull request #2888
Opened 2018-07-10 13:30 UTC by 3TUSK

This PR contains a fully-revamped translation of OpenComputer manual. Calling @TartaricAcid, @ZeroAurora and @JackyWangMislantiaJnirvana for review, don't merge it yet.  

Targeting `master-MC1.12` only, as all file names are lowercased. 

Also, CC @tongkl1 as he did #2839.

2018-07-10 14:40 UTC, ZeroAurora requested changes

2018-07-10 14:40 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/disk.md
>  ![World. RIP Terry Pratchett.](oredict:oc:materialDisk)
"这个世界。愿特里·普拉切特安息。（特里·普拉切特创作了幽默奇幻小说《蝶形世界》，然而书名直译过来就是“磁盘世界”）"

2018-07-10 14:40 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/analyzer.md
> +![Must. Resist. Bad. Joke.](oredict:oc:analyzer)
Must. Resist. Bad. Joke. -> 必须。抵制。不当的。玩笑。

2018-07-10 14:44 UTC, ZeroAurora requested changes

2018-07-10 14:44 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/disk.md
> +![World. RIP Terry Pratchett.](oredict:oc:materialDisk)
"这个世界。愿特里·普拉切特安息。（特里·普拉切特创作了幽默奇幻小说《蝶形世界》，然而书名直译过来就是“磁碟世界”）"

2018-07-11 12:15 UTC, ZeroAurora requested changes

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/block/disassembler.md
> +![Build it, tear it down.](oredict:oc:disassembler)
建造它，再把它拆了。

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/block/diskdrive.md
> +![Going round and round and...](oredict:oc:diskDrive)
转啊转啊转……

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/block/hologram1.md
> +![Is this the real life? Is this just fantasy?](oredict:oc:hologram1)
这是真实的生活吗？还是只是幻想？（出自歌曲：Queen - Bohemian Rhapsody）

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/block/microcontroller.md
> +![Don't belittle it.](block:OpenComputers:microcontroller)
可别小看它

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/block/motionsensor.md
> +![Don't. Blink.](oredict:oc:motionSensor)
别。眨眼。

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/block/rack.md
> +![Free housing.](oredict:oc:rack)
免费居住。

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/block/relay.md
> +![Building bridges.](oredict:oc:relay)
架起心灵之桥。

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/block/robot.md
> +![His name was Tobor.](block:OpenComputers:robot)
他叫 Tobor。（Tobor 出自 "Tobor the Great"，一个 1954 年的美国黑白科幻电影）

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/general/quickstart.md
> +![No, it's not a flatscreen.](oredict:oc:screen2)
不，这可不是平板屏。

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/general/quickstart.md
> +![It lives!](opencomputers:doc/img/configuration_done.png)
它活了！（出自游戏《以撒之困》）

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/controlunit.md
>  ![With built-in cruise control.](oredict:oc:materialCU)
现已内置巡航控制系统。

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/databaseupgrade1.md
> +![Living in the database.](oredict:oc:databaseUpgrade1)
住在数据库里。（出自动画系列《记录的地平线》）

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/dronecase1.md
> +![Droning on.](oredict:oc:droneCase1)
嗡嗡嗡（drone 也可代表雄峰的意思）

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/eeprom.md
> +![Let's get this party started.](oredict:oc:eeprom)
派对开始！

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/experienceupgrade.md
> +![This makes no sense, but it's cool.](oredict:oc:experienceUpgrade)
这没有什么意义，但这很酷。

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/graphicscard1.md
> +![Fancy images.](oredict:oc:graphicsCard1)
炫彩图像。

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/hoverboots.md
> +![Step on it.](oredict:oc:hoverBoots)
赶快！（直译过来是“踩在它上面”）

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/hoverupgrade1.md
> +![Float like a feather.](oredict:oc:hoverUpgrade1)
像羽毛一样漂浮（出自歌曲：Radiohead - Creep）

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/inventorycontrollerupgrade.md
> +![I'm in control.](oredict:oc:inventoryControllerUpgrade)
我被控制了。

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/linkedcard.md
> +![I feel we some kind of connection.](oredict:oc:linkedCard)
我觉得我们之间有种微妙的关系。

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/nanomachines.md
> +![Nanomachines, son.](oredict:oc:nanomachines)
出自《合金装备反叛：复仇》

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/ram1.md
> +![Do you remember, dancing in September~](oredict:oc:ram1)
（出自歌曲：Earth Wind & Fire - September）

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/solargeneratorupgrade.md
> +![Walking on the sun.](oredict:oc:solarGeneratorUpgrade)
在太阳上行走。

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/tablet.md
> +![Touch me if you can.](item:OpenComputers:item@68)
（出自最终幻想14）

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/tractorbeamupgrade.md
> +![Beam me up.](oredict:oc:tractorBeamUpgrade)
解放我。（直译过来是“把我传过来”）

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/worldsensorcard.md
> +![To boldly go...](oredict:oc:worldSensorCard)
勇敢前进……（出自舒尔茨-马库奇和戴维斯所写的关于火星探索的论文《勇敢前进》，里面提出了单程飞往火星的设想）

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/redstonecard1.md
> +![Seeing red.](oredict:oc:redstoneCard1)
看见红色（在英文里，seeing red 暗示着这个人处于暴怒之中）

2018-07-11 12:15 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/cpu1.md
> +![Braaainz.](oredict:oc:cpu1)
脑~子

2018-07-17 13:08 UTC, FledgeXu commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/cpu1.md
> +![Braaainz.](oredict:oc:cpu1)
<img width="512" alt="c178a26d9bc0f703ebc901029ccf9284" src="https://user-images.githubusercontent.com/16664654/42819202-71c11f2a-8a05-11e8-8e0d-322b4a4e4903.png">
文字有重叠的现象。

2018-07-17 13:54 UTC, 3TUSK commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/cpu1.md
> +![Braaainz.](oredict:oc:cpu1)
@FledgeXu 暂时把 `--` 注释去掉了。应该是 OC 本身的问题。

2018-07-26 15:29 UTC, JackyJnirvana requested changes

2018-07-26 15:29 UTC, JackyJnirvana commented on src/main/resources/assets/opencomputers/doc/zh_cn/block/transposer.md
> +# 转运器
建议翻译：数控传输机

2018-07-26 15:29 UTC, JackyJnirvana commented on src/main/resources/assets/opencomputers/doc/zh_cn/block/transposer.md
> +转运器连接了红石控制的漏斗和[机器人](robot.md)，这样[电脑](../general/computer.md)就能控制物品和流体在相邻方块之间的传输了。
[跑腿儿的]
数控传输机用于实现[电脑](../general/computer.md)控制的物品或者流体传输。它能在相邻的容器之间转移物品或者流体，比如用于链接红石控制的漏斗和[机器人](robot.md)

_注意，这个设备没有内部存储空间。_

此外，这个设备还可以用于检测与它相邻的容器装了什么。此时它的行为类似于一个装了[物品栏升级](../item/inventoryControllerUpgrade.md)的[适配器](adapter.md)（当你在检测相邻的箱子里有什么东西的时候）或者一个装了[储罐控制器](../item/tankControllerUpgrade.md)的[适配器](adapter.md)（当你在检测相邻的液槽里有什么东西的时候）

2018-07-26 15:29 UTC, JackyJnirvana commented on src/main/resources/assets/opencomputers/doc/zh_cn/block/transposer.md
> +**注意：本方块没有物品栏。**
（原文不是*斜体*么）
*注意：类似红石力量模组里的传输机，本设备没有内置的物品栏或液槽。它只能使物品或流体在与它相邻的几个容器中转移。*

2018-09-01 04:07 UTC, payonel commented
What is that status of this PR?

2018-09-01 04:24 UTC, ZeroAurora commented
This PR is WIP. We don't have enough time to review all translations in the PR. But we're still trying to squeezing time to review it.

2018-09-01 14:21 UTC, ZeroAurora requested changes
居然有两个 Pending 的 Review……惊了
修改了一点东西

2018-09-01 14:21 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/general/quickstart.md
> +这个时候再尝试启动，它会告诉你电脑需要安装 [CPU](../item/cpu1.md)。CPU 分不同级别，级别越高，能搭配使用的配件就越多，执行速度也越快。稍后你会注意的 OpenComputer 中的很多东西都分级别。所以，挑一块 CPU 然后装进你的[机箱](../block/case1.md)里。
稍后你会注意**到** OpenComputer**s** 中的很多东西都分级别。（错字漏字）

2018-09-01 14:21 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/general/quickstart.md
> +![Partially configured computer.](opencomputers:doc/img/configuration_case2.png)
部分配置好的电脑

2018-09-01 14:21 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/general/lua.md
> +[《Lua 编程手册》](http://www.lua.org/manual/5.2/manual.html)和[《Lua 编程》](http://www.lua.org/pil/) 是学习基本功能并熟悉 Lua标准库的好帮手。虽然 [OpenOS](openOS.md) 尽可能准确地模拟标准库，但它相比于标准的 Lua 仍然有所不同，比如大部分 debug 库的内容出于安全考虑去掉了。所有不同
最好注释“两本书均为英文”

2019-03-09 16:04 UTC, ZeroAurora commented
Any progress in this PR? I still have no time to review.

2019-03-09 18:11 UTC, 3TUSK commented
Distracted by a sheer amount of other things... I will see if I can get free time soon™.

2019-05-06 00:14 UTC, 3TUSK commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/inventorycontrollerupgrade.md
> +![I'm in control.](oredict:oc:inventoryControllerUpgrade)
> in control
> able to direct a situation, person, or activity: from the beginning he has been in control of his own destiny.

其实是反过来的。

2019-05-06 01:01 UTC, 3TUSK commented
@ZeroAurora @JackyWangMislantiaJnirvana @FledgeXu @TartaricAcid 
有时间的话还请帮忙校读一下。

I *think* the translation is ready for the last round of review now - calling for some people for last proofreading.

2019-05-11 10:45 UTC, ZeroAurora commented
准备中考，暂无时间，抱歉。
I'm sorry that I have little time because I'm facing an important examine.


 
---Original---
From: "Urey. Xue"<notifications@github.com>
Date: 2019/5/6 09:01:23
To: "MightyPirates/OpenComputers"<OpenComputers@noreply.github.com>;
Cc: "Mention"<mention@noreply.github.com>;"ZeroAurora"<zeroaurora@qq.com>;
Subject: Re: [MightyPirates/OpenComputers] Revamp zh_cn manual (#2888)



@ZeroAurora @JackyWangMislantiaJnirvana @FledgeXu @TartaricAcid
 有时间的话还请帮忙校读一下。
 
I think the translation is ready for the last round of review now - calling for some people for last proofreading.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-05-11 13:06 UTC, JackyWangMislantiaJnirvana commented
> @ZeroAurora @JackyWangMislantiaJnirvana @FledgeXu @TartaricAcid
> 有时间的话还请帮忙校读一下。
> 
> I _think_ the translation is ready for the last round of review now - calling for some people for last proofreading.

准备高考，暂无时间，抱歉。26天之后复活。
I'm sorry for not being able to contribute because of the approaching GaoKao(Chinese Collage entrance exam). WILL be active after 26 days.

2019-06-19 04:45 UTC, FledgeXu commented
`terminal`  被翻译成`远程终端`是不是有点问题？一般使用的时候直接用`终端`的。

2019-06-19 04:47 UTC, FledgeXu requested changes
`oc:gui.Switch.TransferRate=周期率`这里应该是`传输率`？

2019-06-19 15:41 UTC, SeraphJACK approved these changes

2019-06-19 23:04 UTC, xiaoxi654 commented
> `oc:gui.Switch.TransferRate=周期率`这里应该是`传输率`？

我认为 `传输速率` 在这个语境下可能更好一些吧？

2019-06-23 02:56 UTC, 3TUSK commented
Done:
 - "Cycle Rate" -> “传输速率”
 - "Remote Terminal" -> “终端”

2019-06-27 05:29 UTC, ZeroAurora requested changes

2019-06-27 05:29 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/tabletCase1.md
> +- 1x [升级](upgradeContainer3.md)或 T3 [卡槽](cardContainer3.md)
- 1x [升级组件容器](upgradeContainer3.md)或 T3 [卡槽](cardContainer3.md)

2019-06-27 05:29 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/tabletCase1.md
> +- 1x [升级](upgradeContainer2.md)或 T2 [卡槽](cardContainer2.md)
- 1x [升级组件容器](upgradeContainer2.md)或 T2 [卡槽](cardContainer2.md)

2019-06-27 05:29 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/acid.md
> +可口的[来源请求]混合液体，如果你想找点乐子的话就喝下去吧。或者你想烧了你的食管也可以现在就喝。同时也是制作多种物品的原料。
这是种可口的[谁说的]混合液体。如果你想……找点乐子，或者烧了你的食管，亦或者二者兼得的话，就喝下去吧。同时它也是制作多种更有用物品的原料。

2019-06-27 05:29 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/acid.md
> +其实它还有一个主要用处是从你的系统中移除[纳米机器](nanomachines.md)。这是唯一的方式！
其实它还有一个主要用处是从你的身体系统中移除[纳米机器](nanomachines.md)。这是唯一能够摆脱它们的方式！

2019-06-27 05:29 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/alu.md
> +# 算逻运算单元
算术及逻辑运算部件（下同）

2019-06-27 05:29 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/drone.md
> +![Big brother is trying to watch you.](item:OpenComputers:item@84)
老大哥想看看你（《1984》）

2019-06-27 05:29 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/navigationupgrade.md
> +内部地图可以通过与新地图重新在工作台中合成来更新，旧地图会返还。
安装于内部的地图可以通过与新地图重新在工作台中合成来更新。旧地图会返还给玩家。

2019-06-27 05:29 UTC, ZeroAurora commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/terminalserver.md
> +![遥控视角](oredict:oc:terminalServer)
远程查看

2019-06-30 00:39 UTC, xiaoxi654 commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/acid.md
> +可口的[来源请求]混合液体，如果你想找点乐子的话就喝下去吧。或者你想烧了你的食管也可以现在就喝。同时也是制作多种物品的原料。
[来源请求] 在 wiki 中比较常见，我认为在这里使用没有什么问题

2019-06-30 02:18 UTC, SeraphJACK commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/acid.md
> +可口的[来源请求]混合液体，如果你想找点乐子的话就喝下去吧。或者你想烧了你的食管也可以现在就喝。同时也是制作多种物品的原料。
原文就是 CitationNeeded 吧

2019-06-30 02:38 UTC, ZeroAurora commented
觉得国内玩家看不懂就换了个都能理解的词，我觉得来源请求没什么问题，但是怎么说…有点生硬了


 
---Original---
From: "Seraph_JACK"<notifications@github.com>
Date: 2019/6/30 10:18:57
To: "MightyPirates/OpenComputers"<OpenComputers@noreply.github.com>;
Cc: "Mention"<mention@noreply.github.com>;"ZeroAurora"<zeroaurora@qq.com>;
Subject: Re: [MightyPirates/OpenComputers] Revamp zh_cn manual (#2888)



@SeraphJACK commented on this pull request.
 
 
In src/main/resources/assets/opencomputers/doc/zh_cn/item/acid.md:
 > @@ -0,0 +1,9 @@ +# 酸液 + +![Reflux?](oredict:oc:materialAcid) + +可口的[来源请求]混合液体，如果你想找点乐子的话就喝下去吧。或者你想烧了你的食管也可以现在就喝。同时也是制作多种物品的原料。  
原文就是 CitationNeeded 吧
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-06-30 12:01 UTC, xiaoxi654 commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/acid.md
> +可口的[来源请求]混合液体，如果你想找点乐子的话就喝下去吧。或者你想烧了你的食管也可以现在就喝。同时也是制作多种物品的原料。
> 原文就是 CitationNeeded 吧

https://en.wikipedia.org/wiki/Citation_needed
在中文维基中对应的条目名称为 `来源请求`

2019-06-30 12:12 UTC, xiaoxi654 commented
> 觉得国内玩家看不懂就换了个都能理解的词，我觉得来源请求没什么问题，但是怎么说…有点生硬了

我觉得这个属于是一个梗了，在有共识的情况下，我认为没有必要去替换就是，毕竟长期以来中文维基百科也有在用这个模板，对应的英文维基百科模板就是`Citation Needed`

2019-08-24 03:28 UTC, 3TUSK commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/worldsensorcard.md
> +![To boldly go...](oredict:oc:worldSensorCard)
翻译应该是对的，但是出处似乎是《Star Trek》系列。https://zh.wikipedia.org/wiki/%E5%89%8D%E4%BA%BA%E6%9C%AA%E8%87%B3%E4%B9%8B%E5%A2%83

2019-08-24 03:30 UTC, 3TUSK commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/tractorbeamupgrade.md
> +![Beam me up.](oredict:oc:tractorBeamUpgrade)
其实就是“传送”，出处《Star Trek》。https://en.wiktionary.org/wiki/beam_up

2019-08-24 03:43 UTC, 3TUSK commented on src/main/resources/assets/opencomputers/doc/zh_cn/item/alu.md
> +# 算逻运算单元
ALU 实际上是个专有名词“算术逻辑单元”。

2019-08-24 03:47 UTC, 3TUSK commented
This PR is ready to go unless there are new comments.

2019-08-24 04:20 UTC, payonel commented
I am glad to hear this PR is ready, but, I would like you to rebase and resolve conflicts so I can merge the PR

2019-08-24 06:50 UTC, 3TUSK commented
> rebase and resolve conflicts

GitHub tells me that there is no merge conflicts. Plus, GitHub does have a squash merge functionality?

2019-08-24 17:02 UTC, payonel commented
you'll have to fix the PR on your own machine and force push the rebased commits, or make a new PR

2019-08-25 00:57 UTC, 3TUSK commented
I am not sure why squash merge is not viable, but here you have the rebased version.

I am not sure why the CI keeps failing, either.

2019-08-25 05:25 UTC, merged