Fix server-side deadlock in filesystem activity handling
MightyPirates/OpenComputers pull request #3013
Opened 2018-12-28 17:26 UTC by ds84182

We've managed to hit a reproducible deadlock concerning filesystems. The exact setup is unknown, but using finer lock scopes should fix the issue.

I'm not able to test this change at the moment (I don't have MCP setup), and I can't verify if the change is valid Scala (but it seems like it should be fine).

2018-12-28 18:56 UTC, Vexatos commented
Where/how exactly would the previous setup deadlock?

2018-12-28 19:15 UTC, notcake commented
```
"Server thread" - Thread t@23
   java.lang.Thread.State: BLOCKED
        at li.cil.oc.server.component.FileSystem.onMessage(FileSystem.scala:273)
        - waiting to lock <44361bdb> (a li.cil.oc.server.fs.FileSystem$BufferedFileSystem) owned by "OpenComputers-Computer-1" t@143
        at li.cil.oc.server.network.Network$$anonfun$send$1.apply(Network.scala:371)
        at li.cil.oc.server.network.Network$$anonfun$send$1.apply(Network.scala:371)
        at scala.collection.immutable.List.foreach(List.scala:383)
        at li.cil.oc.server.network.Network.send(Network.scala:371)
        at li.cil.oc.server.network.Network.sendToReachable(Network.scala:205)
        at li.cil.oc.server.network.Network$Wrapper.sendToReachable(Network.scala:773)
        at li.cil.oc.server.network.Network$Wrapper.sendToReachable(Network.scala:749)
        at li.cil.oc.server.network.NodeVarargPart$class.sendToReachable(Node.scala:104)
        at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.sendToReachable(Network.scala:636)
        at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.sendToReachable(Network.scala:636)
        at li.cil.oc.server.machine.Machine.start(Machine.scala:235)
        - locked <6c260115> (a scala.collection.mutable.Stack)
        at li.cil.oc.server.machine.Machine.update(Machine.scala:547)
        at li.cil.oc.server.component.Server.update(Server.scala:206)
        at li.cil.oc.common.inventory.ComponentInventory$class.updateComponents(ComponentInventory.scala:47)
        at li.cil.oc.common.tileentity.Rack.updateComponents(Rack.scala:34)
        at li.cil.oc.common.tileentity.Rack.updateEntity(Rack.scala:389)
        at li.cil.oc.common.tileentity.traits.Tickable$class.update(Tickable.scala:6)
        at li.cil.oc.common.tileentity.Rack.func_73660_a(Rack.scala:34)
        at net.minecraft.world.World.func_72939_s(World.java:1835)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
- None

"OpenComputers-Computer-1" - Thread t@143
   java.lang.Thread.State: BLOCKED
        at li.cil.oc.server.PacketSender$.sendFileSystemActivity(PacketSender.scala:135)
        - waiting to lock <751c6e49> (a scala.collection.mutable.WeakHashMap) owned by "OpenComputers-Computer-3" t@145
        at li.cil.oc.server.component.FileSystem.diskActivity(FileSystem.scala:365)
        at li.cil.oc.server.component.FileSystem.open(FileSystem.scala:169)
        - locked <44361bdb> (a li.cil.oc.server.fs.FileSystem$BufferedFileSystem)
        at generated.li.cil.oc.CallWrapper_li_cil_oc_server_component_FileSystem_open.call(Unknown Source)
        at li.cil.oc.server.machine.Callbacks$ComponentCallback.apply(Callbacks.scala:123)
        at li.cil.oc.server.network.Component$class.invoke(Component.scala:112)
        at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.invoke(Network.scala:636)
        at li.cil.oc.server.machine.Machine.invoke(Machine.scala:360)
        at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.apply(ComponentAPI.scala:78)
        at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.apply(ComponentAPI.scala:78)
        at li.cil.oc.server.machine.luac.NativeLuaArchitecture.invoke(NativeLuaArchitecture.scala:55)
        at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5.apply(ComponentAPI.scala:78)
        at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5.apply(ComponentAPI.scala:74)
        at li.cil.oc.util.ExtendedLuaState$ExtendedLuaState$$anon$1.invoke(ExtendedLuaState.scala:24)
        at li.cil.repack.com.naef.jnlua.LuaStateFiveThree.lua_resume(Native Method)
        at li.cil.repack.com.naef.jnlua.LuaState.resume(LuaState.java:1758)
        - locked <508d8162> (a li.cil.repack.com.naef.jnlua.LuaStateFiveThree)
        at li.cil.oc.server.machine.luac.NativeLuaArchitecture.runThreaded(NativeLuaArchitecture.scala:230)
        at li.cil.oc.server.machine.Machine.run(Machine.scala:972)
        - locked <6f53cd69> (a li.cil.oc.server.machine.Machine)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
- locked <5ece429e> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"OpenComputers-Computer-3" - Thread t@145
   java.lang.Thread.State: BLOCKED
        at li.cil.oc.server.machine.Machine.isRunning(Machine.scala:199)
        - waiting to lock <6c260115> (a scala.collection.mutable.Stack) owned by "Server thread" t@23
        at li.cil.oc.server.component.Server.getCurrentState(Server.scala:225)
        at li.cil.oc.common.tileentity.Rack.isWorking(Rack.scala:452)
        at li.cil.oc.common.tileentity.Rack$$anonfun$hasRedstoneCard$1.apply(Rack.scala:455)
        at li.cil.oc.common.tileentity.Rack$$anonfun$hasRedstoneCard$1.apply(Rack.scala:454)
        at scala.collection.IndexedSeqOptimized$class.prefixLengthImpl(IndexedSeqOptimized.scala:38)
        at scala.collection.IndexedSeqOptimized$class.exists(IndexedSeqOptimized.scala:46)
        at scala.collection.mutable.ArrayOps$ofRef.exists(ArrayOps.scala:186)
        at li.cil.oc.common.tileentity.Rack.hasRedstoneCard(Rack.scala:454)
        at li.cil.oc.common.tileentity.Rack.markChanged(Rack.scala:269)
        at li.cil.oc.common.event.FileSystemAccessHandler$$anonfun$onFileSystemAccess$1.apply$mcVI$sp(FileSystemAccessHandler.scala:27)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
        at li.cil.oc.common.event.FileSystemAccessHandler$.onFileSystemAccess(FileSystemAccessHandler.scala:21)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1556_FileSystemAccessHandler$_onFileSystemAccess_Server.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
        at li.cil.oc.server.PacketSender$.sendFileSystemActivity(PacketSender.scala:143)
        - locked <751c6e49> (a scala.collection.mutable.WeakHashMap)
        at li.cil.oc.server.component.FileSystem.diskActivity(FileSystem.scala:365)
        at li.cil.oc.server.component.FileSystem.open(FileSystem.scala:169)
        - locked <6593932a> (a li.cil.oc.server.fs.FileSystem$BufferedFileSystem)
        at generated.li.cil.oc.CallWrapper_li_cil_oc_server_component_FileSystem_open.call(Unknown Source)
        at li.cil.oc.server.machine.Callbacks$ComponentCallback.apply(Callbacks.scala:123)
        at li.cil.oc.server.network.Component$class.invoke(Component.scala:112)
        at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.invoke(Network.scala:636)
        at li.cil.oc.server.machine.Machine.invoke(Machine.scala:360)
        at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.apply(ComponentAPI.scala:78)
        at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5$$ano [...]

2018-12-28 19:17 UTC, ds84182 commented
@Vexatos Essentially, we have a deadlock between 3 threads: The server thread, and two OC computer threads.

The server thread was in the middle of starting a computer and sending a computer.start network message. [Code](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/machine/Machine.scala#L233) This attempts to lock a Filesystem component for network message deliver, but the Filesystem component is currently locked by the first OC thread.

The first OC thread was in the middle of attempting to send a filesystem activity packet, in `sendFileSystemActivity`. However, the `fileSystemAccessTimeouts` map is locked by the second OC thread, which was also in the middle of `sendFileSystemActivity`, for a different Filesystem.

The second OC thread, which was also in the middle of attempting to send a filesystem activity packet, entered `FileSystemAccessHandler` via the Forge eventbus. This caused a chain reaction where calling `markChanged` on the associated server rack caused a cascade that eventually got to `Machine.isRunning`, which tries to lock the state of the machine being started on the server thread.

Stack trace dumps available here:

[Server thread](https://gist.github.com/SwadicalRag/ef17cc00e72a0d4bb971491497eef96d#file-thread-dumb-L1066)

[First OpenComputers thread](https://gist.github.com/SwadicalRag/ef17cc00e72a0d4bb971491497eef96d#file-thread-dumb-L419)

[Second OpenComputers thread](https://gist.github.com/SwadicalRag/ef17cc00e72a0d4bb971491497eef96d#file-thread-dumb-L332)

The main issue comes from the lock on `fileSystemAccessTimeouts`.

2018-12-28 19:22 UTC, Vexatos requested changes

2018-12-28 19:22 UTC, Vexatos commented on src/main/scala/li/cil/oc/server/PacketSender.scala
>        case Some(hostTimeouts) if hostTimeouts.getOrElse(name, 0L) > System.currentTimeMillis() => // Cooldown.
These `hostTimeouts` are not synchronized and could _potentially_ cause CMEs. Might have to synchronize those as well?

2019-06-29 07:40 UTC, asiekierka commented
Uh?

2023-06-03 14:39 UTC, asiekierka commented
This has been open for long enough.

2023-06-03 14:39 UTC, closed without merging